### ISSUE TITLE
Error when filebucketing /etc/localtime

### ISSUE THREAD

**Issue by phathocker** [saz/puppet-timezone#24]
Possibly because of https://tickets.puppetlabs.com/browse/PUP-1334?

Also could be because changing from file to symlink?
<pre>
before:
-rw-r--r--. 1 root root 3543 Nov 20 15:58 /etc/localtime

after:
lrwxrwxrwx 1 root root 35 Apr 20 23:29 /etc/localtime -> /usr/share/zoneinfo/America/Chicago
</pre>

Output:
<pre>
Info: Applying configuration version 'ca129a826365903363f5ee990f92006e404a6054'
Info: Computing checksum on file /etc/localtime
Error: Could not back up /etc/localtime: Error 400 on SERVER: Got passed new contents for sum {md5}5f043232843c6d067008d64a60bcff51
Error: Could not back up /etc/localtime: Error 400 on SERVER: Got passed new contents for sum {md5}5f043232843c6d067008d64a60bcff51
Error: /Stage[main]/Timezone/File[/etc/localtime]/ensure: change from file to link failed: Could not back up /etc/localtime: Error 400 on SERVER: Got passed new contents for sum {md5}5f043232843c6d067008d64a60bcff51
</pre>

**Comment by saz** [comment]
This error should be fixed in master

**Comment by phathocker** [comment]
I just tested on one server and I'm still having an issue.  I have a support case open with PL and they are saying it might be related to PE 3.7.0 and I should upgrade to latest 3.7 or 3.8 code.

https://tickets.puppetlabs.com/browse/ENTERPRISE-466

**Comment by phathocker** [comment]
Looks like the fix for me was in PE 3.7.2 or 3.8.  Thanks!
