### ISSUE TITLE
Debian 9 - Incompatibility

### ISSUE THREAD

**Issue by johnny564** [saz/puppet-timezone#49]
Timezone not updated - due tu new behavior described here:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813226

**Comment by saz** [comment]
This should be fixed in the current master.

**Comment by olevole** [comment]
Hmm, I still see this problem on latest  ( 69178c764f6b911a22777f951a71b6bbc8d33cb9 ) version:
~~~
lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.2 (stretch)
Release:        9.2
Codename:       stretch
~~~

hiera:
~~~
timezone::timezone: Europe/Moscow
~~~

Puppet apply:
~~~
..
Notice: /Stage[main]/Timezone/File[/etc/localtime]/target: target changed '/usr/share/zoneinfo/Europe/Moscow' to '../W-SU'
~~~

cat /etc/timezone
~~~
Europe/Moscow
~~~


zdump -v /etc/localtime 
~~~
/etc/localtime  -9223372036854775808 = NULL
/etc/localtime  -9223372036854689408 = NULL
/etc/localtime  9223372036854689407 = NULL
/etc/localtime  9223372036854775807 = NULL
~~~

date
~~~
Fri Nov 24 11:24:51 UTC 2017
~~~

But after manual "dpkg-reconfigure -fnoninteractive tzdata" all fine:
~~~
% dpkg-reconfigure -fnoninteractive tzdata

Current default time zone: 'Europe/Moscow'
Local time is now:      Fri Nov 24 14:26:29 MSK 2017.
Universal Time is now:  Fri Nov 24 11:26:29 UTC 2017.

% zdump -v /etc/localtime 
...
/etc/localtime  Sat Oct 25 21:59:59 2014 UT = Sun Oct 26 01:59:59 2014 MSK isdst=0 gmtoff=14400
/etc/localtime  Sat Oct 25 22:00:00 2014 UT = Sun Oct 26 01:00:00 2014 MSK isdst=0 gmtoff=10800
/etc/localtime  9223372036854689407 = NULL
/etc/localtime  9223372036854775807 = NULL

% date
Fri Nov 24 14:27:22 MSK 2017
~~~

However, after the next session, it returns:
~~~
% puppet agent -t
...
Notice: /Stage[main]/Timezone/File[/etc/localtime]/target: target changed '/usr/share/zoneinfo/Europe/Moscow' to '../W-SU'
Notice: Applied catalog in 5.44 seconds

% date
Fri Nov 24 11:28:23 UTC 2017
~~~

**Comment by olevole** [comment]
@saz do you have any ideas?
